name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ./.github/actions/setup-nix
      - name: Lint
        run: |
          eval "$(nix print-dev-env .#ci)"
          just format-check
          just lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neovim: [stable, nightly]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7 # v1
        with:
          neovim: true
          version: ${{ matrix.neovim }}
      - name: Run tests
        run: nvim --headless -l tests/minit.lua
      - name: Run E2E tests
        run: nvim --headless -l tests/e2e_minit.lua

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ./.github/actions/setup-nix
      - name: Generate vimdoc
        run: |
          eval "$(nix print-dev-env .#ci)"
          GITHUB_ACTIONS= just doc
      - name: Check vimdoc is up to date
        run: git diff --exit-code doc/eda.nvim.txt
